### ISSUE TITLE
how to reproduce the baseline (MATIS Frame) results? the config file, data, and the code 

### ISSUE THREAD

**Issue by wenxixi** [BCV-Uniandes/MATIS#2]
Hi,

Thanks for your work and for sharing the code!

I am interested in how you obained the baseline (MATIS Frame) results. Could you please kindly share the code, and config, and the data organisation for running inference on the MATIS frame model to obtain the reported baseline results? 

Thank you in adanvce!

**Comment by nayobi** [comment]
Hello, we provide instructions on how to reproduce the segmentation baseline in the extended version of our work. Please check the MATIS baseline section in this [link](https://github.com/BCV-Uniandes/GraSP/tree/main/TAPIS) and let us know if you need help with anything else.
