### ISSUE TITLE
Hello, I would like to ask if your data can be packaged into a compressed package. . .

### ISSUE THREAD

**Issue by jiajia131** [BCV-Uniandes/MATIS#3]

**Comment by jiajia131** [comment]
It’s okay, it turns out that there is a ‘/’ missing at the end of the command.
$ wget -r http://157.253.243.19/MATIS/

**Comment by nayobi** [comment]
Hello, we have modified our download links. You can now download a compressed archive with wget or from the provided Google Drive link. Please check the updated download instructions in the README file and let us know if you are still having trouble.
